### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lethunder** [RomanHargrave/bitwarden-rs-nginx-docker#1]
Hello,
can you explain how to install this please?

**Comment by RomanHargrave** [comment]
Sorry for the late reply. You'll need to build the container using `docker build` and then deploy it with `docker container create` or `docker run`. Be sure to set the environment variables listed in the `bitwarden_rs` README as well as any additional environment variables from this repo's README.

**Comment by lethunder** [comment]
Thanks a lot

Le mer. 26 févr. 2020 à 00:49, Roman Hargrave <notifications@github.com> a
écrit :
